

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      # Expose container port 8000 on host port 80 for public access on EC2
      - "80:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: hello
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      SECRET_KEY: abc

volumes:
  postgres_data:
